### PR TITLE
Latest Version

### PR DESCRIPTION
**Pull request by KMastroluca**

### CODE REVIEW

**Comment by PThorpe92** [comment]
OK So we are going to have `0` be the location for AWAY:

so any time a resident scans twice in the same location, their location will be zero.. so you can just `POST /api/timestamps`

```json
  [
    {
        "scan_location": 69,
        "rfid": "284752935625625623"
    }
 ]
```
If I have resident `"284752935625625623"` with `69` for his current_location: I will return

```json
  [
    {
        "rfid": "284752935625625623",
        "current_location": 0
    }
 ]
```
and if their location is 0, you can prompt the resident for a new location, and then send another POST... (lets say they enter 420)

```json
  [
    {
        "rfid": "284752935625625623",
        "current_location": 420
    }
 ]
```

**Comment by KMastroluca** [comment]
ok

**Comment by PThorpe92** [comment]
Do you want a timestamp returned as well?

**Comment by KMastroluca** [comment]
Sorry I just had a meeting with Lori, im trying to figure out where the fuck im going when I get outta here, its stressing me the fuck out.

I dont think you need to return a Timestamp for this, but my question is this. So on the first scan when someone is at their home unit and they want to go somewhere else, they scan, the client sends a timestamp to location 0, the backend will recognize that as "This person wants so go somewhere" and sends back an instruction for the client to prompt the user for where he is going. Then after confirmation of that, the client will send a second timestamp with the location of the place they selected. Right?

My question is, does the first timestamp to location 0 get thrown out? Simply being used to communicate that a resident wishes to leave?

**Comment by KMastroluca** [comment]
Because im just gonna grab all the timestamps and sift thru them and do joins to construct the various tables I want. I need to know if I need to throw out all location:0 timestamps. Because those would be confusing to anyone looking at the timestamps I think.

**Comment by KMastroluca** [comment]
Which is why, no, I dont think I need you to return a timestamp, it will simply update when it needs to update.

**Comment by KMastroluca** [comment]
However I decide to do that, im gonna make sure that you're never gonna be looking at old information

**Comment by PThorpe92** [comment]
No so on the first scan.. (every scan):  the ONLY location you send is the location of whatever location you have in local storage. that happens every time..
IF you get a RETURN that has location 0.. then you prompt the user for a destination, and THEN you can send a timestamp with a different location. (and therefore getting back a new current_location that isn't zero for the user)

**Comment by KMastroluca** [comment]
Okay okay, but the initial, this is where I am timestamp is a throwaway right because we only care about where the person went, not where they came from, because we can infer from the last timestamp where they were before.

**Comment by KMastroluca** [comment]
I totally understand whats happening now, I just need to know how im going to have to parse incoming timestamps.

**Comment by KMastroluca** [comment]
And if that is the case, then yes you will need to return the timestamp after the first scan, but not after the second one because i will just hit the api and update the list.

**Comment by PThorpe92** [comment]
Ok so i handled a bunch of the error stuff; the problem is now i gotta handle all the cases where shit like this happens. but either way, all the JSON now gives you info
image

**Comment by KMastroluca** [comment]
Awesome.

**Comment by KMastroluca** [comment]
Im adjusting my code that extracts priority timestamps

**Pull request merged**
